language: node_js
node_js:
    - "6"
env:
  global:
    - "FTP_USER=14-forty.com"
    - "FTP_PASSWORD=c6xvbrQE41na/icGcsXIofkEeiEJvrvUtovkcSKryqufApe/iXyPNXGJCq25yOZ8iIhl13UQkJNl9gaTDYfT7lltaeZRFN+1nAsrzMOQWQPuggMabyBgIhfhuLoZ31sRKb0J5zx/v4to580ypaiXPnICJOmYO9R/5BNd5nZiZ5ZmEsOcPbUk11VurKX549SEfkAJHJQ7dqv6z+gcn3Qc6nec/xZdgeZKjat8jdOIv0cPTzVHAhPmnz425l7C3e5pHGsTb2KhTzBVX45NrrJSqe765qc8xZGjdOLZFYHN1MCuzBlo+w7+G/IY9bWFvG2TkMVxVycDHqGfNLxzrD3bNCnT4xYq0fBEYQW6kFeIM/muWH/JaykFDANKsReUOK5qLr0KM9/+wen8tbAncmaU2M2vV1ue8d22DesjYrPGtzrA4q/WwGEL6vtR/gQ+7n4BQy4P0gEfE59bahJIVcWZf7ExIlsq71SeN2nCnyrn9pFYEY5wH+LobC6znsCiVMX5NHibNd1USVuDGieibGDtuScRUkGyAAv6ju4zH9PMQ9TfOwm3PH2Q4WBdX6H1A4gZzMDu0IQNt3dJxs7uBYLLBK63uFsxMmT03T0DetmxmFozM0myHd/ob05gjV16cppi7YQGmxyHB5t0+wOVCqjzkvxUhBiSf68A4s1x69Zlslk="
before_script:
    - npm install
after_success:
    - npm run build